In [1]:
ColabNotebook = 'google.colab' in str(get_ipython())

if ColabNotebook:
    # monta G-drive en entorno COLAB
    from google.colab import drive
    drive.mount('/content/drive/')

    # carpeta donde se encuentran archivos .py auxiliares
    FUENTES_DIR = '/content/drive/MyDrive/Colab Notebooks/FUENTES/'
    DATOS_DIR = '/content/drive/MyDrive/Colab Notebooks/DATOS/'      # carpeta donde se encuentran los datasets
else:
    # configuración para notebook con instalación LOCAL
    FUENTES_DIR = '../FUENTES'         # carpeta donde se encuentran archivos .py auxiliares
    DATOS_DIR   = '../DATOS/' # carpeta donde se encuentran los datasets

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

In [3]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.utils import to_categorical

import numpy as np
from sklearn import preprocessing, metrics, model_selection 
import pandas as pd

In [4]:
df = pd.read_csv(DATOS_DIR + 'Iris.csv')

# Tomamos todas las columnas menos la última
X = np.array(df.iloc[:, 0:-1])
T = np.array(df.iloc[:,-1])
encoder = preprocessing.LabelEncoder()
T = encoder.fit_transform(T)
print(T)

etiquetas = encoder.inverse_transform([0,1,2])
print("\n\n Etiquetas = ",etiquetas)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


 Etiquetas =  ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [5]:
#--- CONJUNTOS DE ENTRENAMIENTO Y TESTEO ---
X_train, X_test, T_train, T_test = model_selection.train_test_split(
        X, T, test_size=0.30) #, random_state=42)

T_trainB = to_categorical(T_train)

In [6]:
normalizarEntrada = 1  # 1 si normaliza; 0 si no

if normalizarEntrada:
    # Escala los valores entre 0 y 1
    #scaler = preprocessing.MinMaxScaler()
    # Normalización usando media y desvio
    scaler = preprocessing.StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

### Definición del modelo

In [7]:

# Crear un modelo de capas secuenciales
model=Sequential()

# Agregar las capas al modelo
model.add(Dense(2, input_shape=[4], activation='tanh'))
model.add(Dense(3, activation='sigmoid'))

# Imprimir un resumen del modelo
model.summary()



C:\Users\Usuario\.venv-3.12\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19 (76.00 B)

 Trainable params: 19 (76.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
# Configuración para entrenamiento
#model.compile(optimizer='sgd', loss='mse', metrics='accuracy')

# Corrected compile + fit lines
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])


In [11]:
model.fit(X_train,T_trainB, epochs=500)

Epoch 1/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3905 - loss: 1.0601  
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4095 - loss: 1.0480 
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4381 - loss: 1.0359 
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4381 - loss: 1.0222 
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4381 - loss: 1.0101 
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4571 - loss: 0.9982 
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4857 - loss: 0.9866 
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5238 - loss: 0.9760 
Epoch 9/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5333 - loss: 0.9657 
Epoch 10/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5524 - loss: 0.9561 
Epoch 11/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5524 - loss: 0.9456 
Epoch 12/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5619 - lo

In [12]:
# Evaluación del modelo
score = model.evaluate(X_train, T_trainB) 

print('Error :', score[0]) 
print('Accuracy:', score[1])


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9524 - loss: 0.2732 
Error : 0.27319246530532837
Accuracy: 0.9523809552192688


In [13]:
# predecir la salida del modelo
Y_pred = model.predict(X_train)

# Convertir la salida del modelo en un número entero
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos : %.3f" % metrics.accuracy_score(T_train, Y_pred2))
print(Y_pred[:5,:])
print(Y_pred2[:5])

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
% aciertos : 0.952
[[0.48832825 0.8571416  0.6062727 ]
 [0.93231744 0.4562653  0.04412699]
 [0.93268955 0.45521063 0.04380317]
 [0.06860992 0.77772856 0.9114615 ]
 [0.9335252  0.44928423 0.04272379]]
[1 0 0 2 0]


In [14]:
report = metrics.classification_report(T_train, Y_pred2, target_names=etiquetas)
print("Training metrics:\n%s" % report) 

MM = metrics.confusion_matrix(T_train, Y_pred2)
print("Confusion matrix:\n%s" % MM)

Training metrics:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        35
Iris-versicolor       0.97      0.89      0.93        35
 Iris-virginica       0.89      0.97      0.93        35

       accuracy                           0.95       105
      macro avg       0.95      0.95      0.95       105
   weighted avg       0.95      0.95      0.95       105

Confusion matrix:
[[35  0  0]
 [ 0 31  4]
 [ 0  1 34]]


In [15]:
# predecir la salida del modelo
Y_pred = model.predict(X_test)
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos X_train : %.3f" % metrics.accuracy_score(T_test, Y_pred2))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
% aciertos X_train : 0.933


In [16]:
report = metrics.classification_report(T_test, Y_pred2, target_names=etiquetas)

print("Métricas de la clasificación:\n%s" % report) 

Métricas de la clasificación:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.93      0.87      0.90        15
 Iris-virginica       0.88      0.93      0.90        15

       accuracy                           0.93        45
      macro avg       0.93      0.93      0.93        45
   weighted avg       0.93      0.93      0.93        45



In [17]:
MM = metrics.confusion_matrix(T_test, Y_pred2)

print("Confusion matrix:\n%s" % MM)
# Convertimos la matriz de confusión en un DataFrame con etiquetas
df_cm = pd.DataFrame(MM, index=etiquetas, columns=etiquetas)

# Mostramos el DataFrame resultante
print("\n\n",df_cm)

Confusion matrix:
[[15  0  0]
 [ 0 13  2]
 [ 0  1 14]]


                  Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               15                0               0
Iris-versicolor            0               13               2
Iris-virginica             0                1              14


In [18]:
capaOculta = model.layers[0]
W1, b1 = capaOculta.get_weights()

capaSalida = model.layers[1]
W2,b2 = capaSalida.get_weights()

print("W1")
print(W1)

print("b1")
print(b1)

print("W2")
print(W2)

print("b2")
print(b2)

W1
[[-0.25266463 -0.11381371]
 [ 0.09149117 -0.76785964]
 [ 0.7223812   0.352434  ]
 [ 1.330437    1.4336048 ]]
b1
[-0.5991974  0.3925071]
W2
[[-2.104069   -0.84462166  1.3180858 ]
 [-0.7337801   1.5085905   1.5484755 ]]
b2
[-0.17634338  0.44515115 -0.26880774]


In [16]:
#model.save("IRIS_Sigmoid.h5")