In [1]:
ColabNotebook = 'google.colab' in str(get_ipython())

if ColabNotebook:
    # monta G-drive en entorno COLAB
    from google.colab import drive
    drive.mount('/content/drive/')

    # carpeta donde se encuentran archivos .py auxiliares
    FUENTES_DIR = '/content/drive/MyDrive/Colab Notebooks/FUENTES/'
    DATOS_DIR = '/content/drive/MyDrive/Colab Notebooks/DATOS/'      # carpeta donde se encuentran los datasets
else:
    # configuración para notebook con instalación LOCAL
    FUENTES_DIR = '../Fuentes'         # carpeta donde se encuentran archivos .py auxiliares
    DATOS_DIR   = '../Datos/' # carpeta donde se encuentran los datasets

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

In [2]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.utils import to_categorical

import numpy as np
from sklearn import preprocessing, metrics, model_selection 
import pandas as pd

In [3]:
df = pd.read_csv(DATOS_DIR + 'Iris.csv')

# Tomamos todas las columnas menos la última
X = np.array(df.iloc[:, 0:-1])
T = np.array(df.iloc[:,-1])
encoder = preprocessing.LabelEncoder()
T = encoder.fit_transform(T)
print(T)

etiquetas = encoder.inverse_transform([0,1,2])
print("\n\n Etiquetas = ",etiquetas)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


 Etiquetas =  ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [4]:
#--- CONJUNTOS DE ENTRENAMIENTO Y TESTEO ---
X_train, X_test, T_train, T_test = model_selection.train_test_split( \
        X, T, test_size=0.30) #, random_state=42)

T_trainB = to_categorical(T_train)

In [5]:
normalizarEntrada = 1  # 1 si normaliza; 0 si no

if normalizarEntrada:
    # Escala los valores entre 0 y 1
    #scaler = preprocessing.MinMaxScaler()
    # Normalización usando media y desvio
    scaler = preprocessing.StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

### Definición del modelo

In [6]:

# Crear un modelo de capas secuenciales
model=Sequential()

# Agregar las capas al modelo
model.add(Dense(2, input_shape=[4], activation='tanh'))
model.add(Dense(3, activation='sigmoid'))

# Imprimir un resumen del modelo
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 10        
                                                                 
 dense_1 (Dense)             (None, 3)                 9         
                                                                 
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [7]:
# Configuración para entrenamiento
#model.compile(optimizer='sgd', loss='mse', metrics='accuracy')

model.compile(optimizer='sgd', loss='mse', metrics='accuracy')


In [8]:
model.fit(X_train,T_trainB, epochs=500)

Epoch 1/500
4/4 [==============================] - 1s 2ms/step - loss: 0.1980 - accuracy: 0.6667
Epoch 2/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1978 - accuracy: 0.6667
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1975 - accuracy: 0.6667
Epoch 4/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1973 - accuracy: 0.6667
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1971 - accuracy: 0.6762
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1969 - accuracy: 0.6857
Epoch 7/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1967 - accuracy: 0.6857
Epoch 8/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1964 - accuracy: 0.6857
Epoch 9/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1962 - accuracy: 0.6857
Epoch 10/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1960 - accuracy: 0.6857
Epoch 11/500
4/4 [===========

4/4 [==============================] - 0s 812us/step - loss: 0.1805 - accuracy: 0.7143
Epoch 85/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1803 - accuracy: 0.7143
Epoch 86/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1801 - accuracy: 0.7143
Epoch 87/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1799 - accuracy: 0.7143
Epoch 88/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1797 - accuracy: 0.7143
Epoch 89/500
4/4 [==============================] - 0s 0s/step - loss: 0.1795 - accuracy: 0.7143
Epoch 90/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1793 - accuracy: 0.7143
Epoch 91/500
4/4 [==============================] - 0s 0s/step - loss: 0.1791 - accuracy: 0.7143
Epoch 92/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1789 - accuracy: 0.7143
Epoch 93/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1788 - accuracy: 0.7143
Epoch 94/500
4/4 [===============

4/4 [==============================] - 0s 2ms/step - loss: 0.1655 - accuracy: 0.7333
Epoch 168/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1654 - accuracy: 0.7333
Epoch 169/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1652 - accuracy: 0.7333
Epoch 170/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1651 - accuracy: 0.7333
Epoch 171/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1649 - accuracy: 0.7333
Epoch 172/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1647 - accuracy: 0.7333
Epoch 173/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1646 - accuracy: 0.7333
Epoch 174/500
4/4 [==============================] - 0s 668us/step - loss: 0.1644 - accuracy: 0.7429
Epoch 175/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1642 - accuracy: 0.7429
Epoch 176/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1641 - accuracy: 0.7429
Epoch 177/500
4/4 [===

Epoch 250/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1528 - accuracy: 0.7810
Epoch 251/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.7714
Epoch 252/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1525 - accuracy: 0.7714
Epoch 253/500
4/4 [==============================] - 0s 0s/step - loss: 0.1524 - accuracy: 0.7714
Epoch 254/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1522 - accuracy: 0.7714
Epoch 255/500
4/4 [==============================] - 0s 0s/step - loss: 0.1521 - accuracy: 0.7714
Epoch 256/500
4/4 [==============================] - 0s 0s/step - loss: 0.1519 - accuracy: 0.7714
Epoch 257/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.7714
Epoch 258/500
4/4 [==============================] - 0s 0s/step - loss: 0.1517 - accuracy: 0.7714
Epoch 259/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1515 - accuracy: 0.7714
Epoch 260/500


4/4 [==============================] - 0s 0s/step - loss: 0.1423 - accuracy: 0.8286
Epoch 333/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1422 - accuracy: 0.8286
Epoch 334/500
4/4 [==============================] - 0s 0s/step - loss: 0.1421 - accuracy: 0.8286
Epoch 335/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1419 - accuracy: 0.8286
Epoch 336/500
4/4 [==============================] - 0s 0s/step - loss: 0.1418 - accuracy: 0.8286
Epoch 337/500
4/4 [==============================] - 0s 438us/step - loss: 0.1417 - accuracy: 0.8286
Epoch 338/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1416 - accuracy: 0.8286
Epoch 339/500
4/4 [==============================] - 0s 0s/step - loss: 0.1415 - accuracy: 0.8286
Epoch 340/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1414 - accuracy: 0.8286
Epoch 341/500
4/4 [==============================] - 0s 0s/step - loss: 0.1413 - accuracy: 0.8286
Epoch 342/500
4/4 [========

4/4 [==============================] - 0s 1ms/step - loss: 0.1335 - accuracy: 0.8381
Epoch 416/500
4/4 [==============================] - 0s 0s/step - loss: 0.1334 - accuracy: 0.8381
Epoch 417/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1333 - accuracy: 0.8381
Epoch 418/500
4/4 [==============================] - 0s 668us/step - loss: 0.1333 - accuracy: 0.8381
Epoch 419/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1332 - accuracy: 0.8381
Epoch 420/500
4/4 [==============================] - 0s 0s/step - loss: 0.1331 - accuracy: 0.8381
Epoch 421/500
4/4 [==============================] - 0s 0s/step - loss: 0.1330 - accuracy: 0.8381
Epoch 422/500
4/4 [==============================] - 0s 0s/step - loss: 0.1329 - accuracy: 0.8381
Epoch 423/500
4/4 [==============================] - 0s 0s/step - loss: 0.1328 - accuracy: 0.8381
Epoch 424/500
4/4 [==============================] - 0s 0s/step - loss: 0.1327 - accuracy: 0.8381
Epoch 425/500
4/4 [=========

4/4 [==============================] - 0s 0s/step - loss: 0.1265 - accuracy: 0.8381
Epoch 499/500
4/4 [==============================] - 0s 927us/step - loss: 0.1264 - accuracy: 0.8381
Epoch 500/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1263 - accuracy: 0.8381


In [9]:
# Evaluación del modelo
score = model.evaluate(X_train, T_trainB) 

print('Error :', score[0]) 
print('Accuracy:', score[1])


4/4 [==============================] - 0s 4ms/step - loss: 0.1263 - accuracy: 0.8381
Error : 0.12628377974033356
Accuracy: 0.8380952477455139


In [10]:
# predecir la salida del modelo
Y_pred = model.predict(X_train)

# Convertir la salida del modelo en un número entero
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos : %.3f" % metrics.accuracy_score(T_train, Y_pred2))
print(Y_pred[:5,:])
print(Y_pred2[:5])

4/4 [==============================] - 0s 3ms/step
% aciertos : 0.838
[[0.1354467  0.5310437  0.5251353 ]
 [0.16503495 0.5528861  0.44041413]
 [0.12424584 0.54348826 0.526393  ]
 [0.80089724 0.28995135 0.25870255]
 [0.8494988  0.24436343 0.27482006]]
[1 1 1 0 0]


In [11]:
report = metrics.classification_report(T_train, Y_pred2, target_names=etiquetas)
print("Training metrics:\n%s" % report) 

MM = metrics.confusion_matrix(T_train, Y_pred2)
print("Confusion matrix:\n%s" % MM)

Training metrics:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        37
Iris-versicolor       0.73      0.71      0.72        31
 Iris-virginica       0.76      0.78      0.77        37

       accuracy                           0.84       105
      macro avg       0.83      0.83      0.83       105
   weighted avg       0.84      0.84      0.84       105

Confusion matrix:
[[37  0  0]
 [ 0 22  9]
 [ 0  8 29]]


In [12]:
# predecir la salida del modelo
Y_pred = model.predict(X_test)
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos X_train : %.3f" % metrics.accuracy_score(T_test, Y_pred2))

2/2 [==============================] - 0s 16ms/step
% aciertos X_train : 0.778


In [13]:
report = metrics.classification_report(T_test, Y_pred2, target_names=etiquetas)

print("Métricas de la clasificación:\n%s" % report) 

Métricas de la clasificación:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      0.92      0.96        13
Iris-versicolor       0.76      0.68      0.72        19
 Iris-virginica       0.62      0.77      0.69        13

       accuracy                           0.78        45
      macro avg       0.80      0.79      0.79        45
   weighted avg       0.79      0.78      0.78        45



In [14]:
MM = metrics.confusion_matrix(T_test, Y_pred2)

print("Confusion matrix:\n%s" % MM)
# Convertimos la matriz de confusión en un DataFrame con etiquetas
df_cm = pd.DataFrame(MM, index=etiquetas, columns=etiquetas)

# Mostramos el DataFrame resultante
print("\n\n",df_cm)

Confusion matrix:
[[12  1  0]
 [ 0 13  6]
 [ 0  3 10]]


                  Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               12                1               0
Iris-versicolor            0               13               6
Iris-virginica             0                3              10


In [15]:
capaOculta = model.layers[0]
W1, b1 = capaOculta.get_weights()

capaSalida = model.layers[1]
W2,b2 = capaSalida.get_weights()

print("W1")
print(W1)

print("b1")
print(b1)

print("W2")
print(W2)

print("b2")
print(b2)

W1
[[-0.21859004  1.0657258 ]
 [ 1.0067291   0.53227115]
 [-0.10477641  0.6133311 ]
 [-0.36767983  0.39515167]]
b1
[-0.12031799 -0.01961109]
W2
[[ 1.329487   -0.7956991   0.1318395 ]
 [-0.7840451  -0.12001047  0.8645483 ]]
b2
[-0.28347936 -0.47401267 -0.28959358]


In [16]:
#model.save("IRIS_Sigmoid.h5")