In [1]:
ColabNotebook = 'google.colab' in str(get_ipython())

if ColabNotebook:
    # monta G-drive en entorno COLAB
    from google.colab import drive
    drive.mount('/content/drive/')

    # carpeta donde se encuentran archivos .py auxiliares
    FUENTES_DIR = '/content/drive/MyDrive/Colab Notebooks/FUENTES/'
    DATOS_DIR = '/content/drive/MyDrive/Colab Notebooks/DATOS/'      # carpeta donde se encuentran los datasets
else:
    # configuración para notebook con instalación LOCAL
    FUENTES_DIR = '../Fuentes'         # carpeta donde se encuentran archivos .py auxiliares
    DATOS_DIR   = '../Datos/' # carpeta donde se encuentran los datasets

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

In [2]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Input, Dense 
from tensorflow.keras.utils import to_categorical

import numpy as np
from sklearn import preprocessing, metrics, model_selection 
import pandas as pd

In [3]:
df = pd.read_csv(DATOS_DIR + 'Iris.csv')

# Tomamos todas las columnas menos la última
X = np.array(df.iloc[:, 0:-1])
T = np.array(df.iloc[:,-1])
encoder = preprocessing.LabelEncoder()
T = encoder.fit_transform(T)
print(T)

etiquetas = encoder.inverse_transform([0,1,2])
print("\n\n Etiquetas = ",etiquetas)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


 Etiquetas =  ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [4]:
#--- CONJUNTOS DE ENTRENAMIENTO Y TESTEO ---
X_train, X_test, T_train, T_test = model_selection.train_test_split( \
        X, T, test_size=0.30) #, random_state=42)

T_trainB = to_categorical(T_train)

In [5]:
normalizarEntrada = 1  # 1 si normaliza; 0 si no

if normalizarEntrada:
    # Escala los valores entre 0 y 1
    #scaler = preprocessing.MinMaxScaler()
    # Normalización usando media y desvio
    scaler = preprocessing.StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

### Definición del modelo

In [6]:

# Crear un modelo de capas secuenciales
model=Sequential()

# Agregar las capas al modelo
model.add(Input(shape=[4]))
model.add(Dense(2, activation='tanh'))
model.add(Dense(3, activation='sigmoid'))

# Imprimir un resumen del modelo
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 10        
                                                                 
 dense_1 (Dense)             (None, 3)                 9         
                                                                 
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [7]:
# Configuración para entrenamiento
#model.compile(optimizer='sgd', loss='mse', metrics='accuracy')

model.compile(optimizer='sgd', loss='mse', metrics=['accuracy'])


In [8]:
model.fit(X_train,T_trainB, epochs=500)

Epoch 1/500
4/4 [==============================] - 1s 5ms/step - loss: 0.2466 - accuracy: 0.2762
Epoch 2/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2462 - accuracy: 0.2762
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2458 - accuracy: 0.2762
Epoch 4/500
4/4 [==============================] - 0s 3ms/step - loss: 0.2453 - accuracy: 0.2762
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2449 - accuracy: 0.2762
Epoch 6/500
4/4 [==============================] - 0s 4ms/step - loss: 0.2444 - accuracy: 0.2762
Epoch 7/500
4/4 [==============================] - 0s 3ms/step - loss: 0.2440 - accuracy: 0.2762
Epoch 8/500
4/4 [==============================] - 0s 1ms/step - loss: 0.2436 - accuracy: 0.2762
Epoch 9/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2432 - accuracy: 0.2762
Epoch 10/500
4/4 [==============================] - 0s 3ms/step - loss: 0.2427 - accuracy: 0.2762
Epoch 11/500
4/4 [===========

4/4 [==============================] - 0s 549us/step - loss: 0.2151 - accuracy: 0.2762
Epoch 85/500
4/4 [==============================] - 0s 0s/step - loss: 0.2147 - accuracy: 0.2762
Epoch 86/500
4/4 [==============================] - 0s 1ms/step - loss: 0.2144 - accuracy: 0.2762
Epoch 87/500
4/4 [==============================] - 0s 0s/step - loss: 0.2141 - accuracy: 0.2762
Epoch 88/500
4/4 [==============================] - 0s 0s/step - loss: 0.2138 - accuracy: 0.2762
Epoch 89/500
4/4 [==============================] - 0s 3ms/step - loss: 0.2134 - accuracy: 0.2762
Epoch 90/500
4/4 [==============================] - 0s 397us/step - loss: 0.2131 - accuracy: 0.2762
Epoch 91/500
4/4 [==============================] - 0s 3ms/step - loss: 0.2128 - accuracy: 0.2762
Epoch 92/500
4/4 [==============================] - 0s 1ms/step - loss: 0.2125 - accuracy: 0.2762
Epoch 93/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2122 - accuracy: 0.2762
Epoch 94/500
4/4 [==============

4/4 [==============================] - 0s 2ms/step - loss: 0.1915 - accuracy: 0.6381
Epoch 168/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1913 - accuracy: 0.6381
Epoch 169/500
4/4 [==============================] - 0s 0s/step - loss: 0.1911 - accuracy: 0.6381
Epoch 170/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1908 - accuracy: 0.6476
Epoch 171/500
4/4 [==============================] - 0s 0s/step - loss: 0.1906 - accuracy: 0.6381
Epoch 172/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1904 - accuracy: 0.6476
Epoch 173/500
4/4 [==============================] - 0s 0s/step - loss: 0.1901 - accuracy: 0.6476
Epoch 174/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1899 - accuracy: 0.6381
Epoch 175/500
4/4 [==============================] - 0s 0s/step - loss: 0.1896 - accuracy: 0.6476
Epoch 176/500
4/4 [==============================] - 0s 0s/step - loss: 0.1894 - accuracy: 0.6476
Epoch 177/500
4/4 [==========

4/4 [==============================] - 0s 3ms/step - loss: 0.1747 - accuracy: 0.6381
Epoch 250/500
4/4 [==============================] - 0s 0s/step - loss: 0.1745 - accuracy: 0.6476
Epoch 251/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1744 - accuracy: 0.6476
Epoch 252/500
4/4 [==============================] - 0s 995us/step - loss: 0.1742 - accuracy: 0.6476
Epoch 253/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1740 - accuracy: 0.6476
Epoch 254/500
4/4 [==============================] - 0s 0s/step - loss: 0.1738 - accuracy: 0.6476
Epoch 255/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1737 - accuracy: 0.6476
Epoch 256/500
4/4 [==============================] - 0s 0s/step - loss: 0.1735 - accuracy: 0.6476
Epoch 257/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1733 - accuracy: 0.6476
Epoch 258/500
4/4 [==============================] - 0s 0s/step - loss: 0.1732 - accuracy: 0.6476
Epoch 259/500
4/4 [=======

4/4 [==============================] - 0s 2ms/step - loss: 0.1624 - accuracy: 0.6762
Epoch 332/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1622 - accuracy: 0.6667
Epoch 333/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1621 - accuracy: 0.6667
Epoch 334/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1620 - accuracy: 0.6667
Epoch 335/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1619 - accuracy: 0.6667
Epoch 336/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1617 - accuracy: 0.6667
Epoch 337/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1616 - accuracy: 0.6667
Epoch 338/500
4/4 [==============================] - 0s 960us/step - loss: 0.1615 - accuracy: 0.6667
Epoch 339/500
4/4 [==============================] - 0s 0s/step - loss: 0.1614 - accuracy: 0.6667
Epoch 340/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1612 - accuracy: 0.6667
Epoch 341/500
4/4 [====

4/4 [==============================] - 0s 0s/step - loss: 0.1533 - accuracy: 0.6762
Epoch 414/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1532 - accuracy: 0.6857
Epoch 415/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1531 - accuracy: 0.6762
Epoch 416/500
4/4 [==============================] - 0s 0s/step - loss: 0.1529 - accuracy: 0.6762
Epoch 417/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1529 - accuracy: 0.6762
Epoch 418/500
4/4 [==============================] - 0s 890us/step - loss: 0.1527 - accuracy: 0.6762
Epoch 419/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1527 - accuracy: 0.6762
Epoch 420/500
4/4 [==============================] - 0s 0s/step - loss: 0.1526 - accuracy: 0.6762
Epoch 421/500
4/4 [==============================] - 0s 985us/step - loss: 0.1525 - accuracy: 0.6762
Epoch 422/500
4/4 [==============================] - 0s 0s/step - loss: 0.1524 - accuracy: 0.6762
Epoch 423/500
4/4 [=====

Epoch 496/500
4/4 [==============================] - 0s 0s/step - loss: 0.1461 - accuracy: 0.7048
Epoch 497/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1461 - accuracy: 0.7048
Epoch 498/500
4/4 [==============================] - 0s 925us/step - loss: 0.1460 - accuracy: 0.7048
Epoch 499/500
4/4 [==============================] - 0s 1ms/step - loss: 0.1459 - accuracy: 0.7048
Epoch 500/500
4/4 [==============================] - 0s 0s/step - loss: 0.1459 - accuracy: 0.7048


In [9]:
# Evaluación del modelo
score = model.evaluate(X_train, T_trainB) 

print('Error :', score[0]) 
print('Accuracy:', score[1])


4/4 [==============================] - 0s 6ms/step - loss: 0.1458 - accuracy: 0.7048
Error : 0.1458057165145874
Accuracy: 0.7047619223594666


In [10]:
# predecir la salida del modelo
Y_pred = model.predict(X_train)

# Convertir la salida del modelo en un número entero
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos : %.3f" % metrics.accuracy_score(T_train, Y_pred2))
print(Y_pred[:5,:])
print(Y_pred2[:5])

4/4 [==============================] - 0s 2ms/step
% aciertos : 0.705
[[0.36615294 0.36358812 0.36600518]
 [0.24857214 0.45424837 0.6088331 ]
 [0.76585454 0.4754258  0.10344305]
 [0.7723172  0.4700755  0.09783775]
 [0.18417323 0.40802842 0.6723234 ]]
[0 2 0 0 2]


In [11]:
report = metrics.classification_report(T_train, Y_pred2, target_names=etiquetas)
print("Training metrics:\n%s" % report) 

MM = metrics.confusion_matrix(T_train, Y_pred2)
print("Confusion matrix:\n%s" % MM)

Training metrics:
                 precision    recall  f1-score   support

    Iris-setosa       0.79      1.00      0.88        37
Iris-versicolor       1.00      0.23      0.38        39
 Iris-virginica       0.57      0.97      0.72        29

       accuracy                           0.70       105
      macro avg       0.79      0.73      0.66       105
   weighted avg       0.81      0.70      0.65       105

Confusion matrix:
[[37  0  0]
 [ 9  9 21]
 [ 1  0 28]]


In [12]:
# predecir la salida del modelo
Y_pred = model.predict(X_test)
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos X_train : %.3f" % metrics.accuracy_score(T_test, Y_pred2))

2/2 [==============================] - 0s 0s/step
% aciertos X_train : 0.778


In [13]:
report = metrics.classification_report(T_test, Y_pred2, target_names=etiquetas)

print("Métricas de la clasificación:\n%s" % report) 

Métricas de la clasificación:
                 precision    recall  f1-score   support

    Iris-setosa       0.81      1.00      0.90        13
Iris-versicolor       1.00      0.09      0.17        11
 Iris-virginica       0.75      1.00      0.86        21

       accuracy                           0.78        45
      macro avg       0.85      0.70      0.64        45
   weighted avg       0.83      0.78      0.70        45



In [14]:
MM = metrics.confusion_matrix(T_test, Y_pred2)

print("Confusion matrix:\n%s" % MM)
# Convertimos la matriz de confusión en un DataFrame con etiquetas
df_cm = pd.DataFrame(MM, index=etiquetas, columns=etiquetas)

# Mostramos el DataFrame resultante
print("\n\n",df_cm)

Confusion matrix:
[[13  0  0]
 [ 3  1  7]
 [ 0  0 21]]


                  Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               13                0               0
Iris-versicolor            3                1               7
Iris-virginica             0                0              21


In [15]:
capaOculta = model.layers[0]
W1, b1 = capaOculta.get_weights()

capaSalida = model.layers[1]
W2,b2 = capaSalida.get_weights()

print("W1")
print(W1)

print("b1")
print(b1)

print("W2")
print(W2)

print("b2")
print(b2)

W1
[[-0.12881538 -0.8177236 ]
 [ 0.38515976  0.09557377]
 [-0.5311076  -0.48988572]
 [-0.5655848  -0.33405098]]
b1
[0.30988085 0.22052893]
W2
[[ 0.88465965  0.34429017 -0.7232203 ]
 [ 0.70998657 -0.21603428 -1.0252869 ]]
b2
[-0.3399856  -0.24134478 -0.505714  ]


In [18]:
#model.save("IRIS_Sigmoid.keras")